name: Purge jsDelivr cache

on:
  push:
    branches:
      - main
    paths:
      - 'headcode.html'

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr cache
        run: |
          curl -X POST "https://purge.jsdelivr.net/gh/nikentropy/entropydesign@main/headcode.html"
